version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: src/Dockerfile
    ports:
      - "3000:3000"
    environment:
      COGNITO_USER_POOL_ID: <USER_POOL_ID>
      COGNITO_CLIENT_ID: <CLIENT_ID>
      POSTGRES_USER: <usuario>
      POSTGRES_PASSWORD: <senha>
      POSTGRES_DB: <banco>
      DB_HOST: postgres
      DB_PORT: 5432
    depends_on:
      - postgres
    command: npm run dev

  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: User
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres-data:
